/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#454747",
        "outline-variant": "#444748",
        "outline": "#8e9192",
        "on-tertiary": "#2f3131",
        "surface-variant": "#353434",
        "primary-fixed-dim": "#c6c6c7",
        "background": "#000000",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-primary": "#5d5f5f",
        "tertiary-container": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-container": "#464747",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-container": "#b6b5b5",
        "surface-bright": "#3a3939",
        "primary-container": "#e2e2e2",
        "primary": "#ffffff",
        "on-background": "#e5e2e1",
        "tertiary": "#ffffff",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353434",
        "secondary": "#c7c6c6",
        "error": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#2f3131",
        "error-container": "#93000a",
        "surface": "#000000",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "on-tertiary-container": "#636565",
        "secondary-fixed": "#e4e2e2",
        "on-primary-fixed": "#1a1c1c",
        "surface-dim": "#141313",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "on-primary-container": "#636565",
        "surface-tint": "#c6c6c7",
        "on-secondary": "#303031",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#464747",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#c4c7c8",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "edge-margin-desktop": "64px",
        "container-max": "1440px",
        "edge-margin-mobile": "24px",
        "section-gap": "120px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-xl": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "900" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
